### ISSUE TITLE
Add docs building to the CI.

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/spec#247] opened 2019-07-25 06:52 UTC
## Problem Definition

The building of the docs is not part of the CI. This can lead to the docs silently not being built for a long time until someone notices.

## Task

Add the docs `make html` to the CI.

**Comment by karlb** [comment] 2019-09-23 12:09
Duplicate of https://github.com/raiden-network/spec/issues/189

**Closed by karlb** 2019-09-23 12:09 UTC
